controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation


#easy_admin_bundle:
  #  resource: 'App/Controller/AdminController'
  #  prefix: /admin
  #  type: annotation